// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6SBsy3ysZ9CvEfdZ4Q92RYZurOW19cdU',
    appId: '1:210928148100:web:dc796efb9c40f92402acd1',
    messagingSenderId: '210928148100',
    projectId: 'citas-eb70d',
    authDomain: 'citas-eb70d.firebaseapp.com',
    storageBucket: 'citas-eb70d.firebasestorage.app',
    measurementId: 'G-VDECFSBJPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZFmdwfMOTVHDKSKie7e12NerIni_iq10',
    appId: '1:210928148100:android:de43368b77a7813f02acd1',
    messagingSenderId: '210928148100',
    projectId: 'citas-eb70d',
    storageBucket: 'citas-eb70d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2HU5JnFHZYDC2h_xA-aovdfIS00um-UY',
    appId: '1:210928148100:ios:c0853afb60f5191f02acd1',
    messagingSenderId: '210928148100',
    projectId: 'citas-eb70d',
    storageBucket: 'citas-eb70d.firebasestorage.app',
    iosBundleId: 'com.example.appCitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2HU5JnFHZYDC2h_xA-aovdfIS00um-UY',
    appId: '1:210928148100:ios:c0853afb60f5191f02acd1',
    messagingSenderId: '210928148100',
    projectId: 'citas-eb70d',
    storageBucket: 'citas-eb70d.firebasestorage.app',
    iosBundleId: 'com.example.appCitas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6SBsy3ysZ9CvEfdZ4Q92RYZurOW19cdU',
    appId: '1:210928148100:web:d15f6019ce9e98e902acd1',
    messagingSenderId: '210928148100',
    projectId: 'citas-eb70d',
    authDomain: 'citas-eb70d.firebaseapp.com',
    storageBucket: 'citas-eb70d.firebasestorage.app',
    measurementId: 'G-7GWC6HBD9P',
  );
}
