import 'package:flutter/foundation.dart';

class Localization extends ChangeNotifier {
  String _languageCode = 'en';

  String get languageCode => _languageCode;

  void setLanguage(String code) {
    _languageCode = code;
    notifyListeners();
  }

  String get(String key) {
    Map<String, String> map;
    switch (_languageCode) {
      case 'es':
        map = _es;
        break;
      case 'fr':
        map = _fr;
        break;
      case 'pt':
        map = _pt;
        break;
      case 'en':
      default:
        map = _en;
    }
    return map[key] ?? key;
  }

  static final Map<String, String> _en = {
    'app_title': 'Space Captain',
    'tactical_log': 'Tactical Log',
    'scan_enemies': 'SCAN FOR ENEMIES',
    'dock_station': 'DOCK AT STATION',
    'attack': 'ATTACK',
    'heal': 'HEAL',
    'flee': 'FLEE',
    'energy': 'ENERGY',
    'credits': 'Credits',
    'hp': 'HP',
    'xp': 'XP',
    'blaster': 'Blaster',
    'plasma_cannon': 'Plasma Cannon',
    'shield': 'Shield',
    'repair': 'Repair',
    'recharge': 'RECHARGE',
    'station_title': 'Space Station Alpha',
    'services': 'Services',
    'full_heal': 'Full Heal',
    'restore_hp': 'Restore 100% HP',
    'armory': 'Armory',
    'travel': 'Travel',
    'go': 'Go',
    'warning_high_level': 'Warning: High Level',
    'shop': 'Shop',
    'buy_credits': 'Buy Credits',
    'real_money': 'Real Money',
    'inventory': 'Inventory',
    'use': 'Use',
    'empty_inventory': 'Inventory is empty',
    'tab_consumables': 'Consumables',
    'tab_equipment': 'Equipment',
    'tab_bank': 'Bank',
    'item_energy_cell': 'Energy Cell',
    'desc_energy_cell': '+50 Energy',
    'item_overcharge': 'Overcharge Chip',
    'desc_overcharge': '+50% Dmg (Next Fight)',
    'item_hyper_shield': 'Hyper-Shield',
    'desc_hyper_shield': 'Start w/ 100 Shield',
    'pack_small': 'Handful of Credits',
    'pack_medium': 'Sack of Credits',
    'pack_large': 'Chest of Credits',
    'item_mega_potion': 'Mega-Potion',
    'desc_mega_potion': 'Heal 150 HP',
    'item_nano_elixir': 'Nano-Elixir',
    'desc_nano_elixir': 'Restore 100 Energy',
    'item_titanium_plating': 'Titanium Plating',
    'desc_titanium_plating': '+20 Max HP',
    'item_neural_link': 'Neural Link',
    'desc_neural_link': '+10 Max Energy',
    'item_pulse_rifle': 'Pulse Rifle',
    'item_neutron_cannon': 'Neutron Cannon',
    'item_singularity': 'Singularity Projector',
    // Omni Realms Expansion
    'world_kingdom_valor': 'Kingdom of Valor',
    'desc_kingdom_valor': 'A medieval land of knights and dragons.',
    'world_jurassica': 'Jurassica',
    'desc_jurassica': 'A prehistoric jungle ruled by dinosaurs.',
    'world_neon_tokyo': 'Neon Tokyo',
    'desc_neon_tokyo': 'A futuristic cyberpunk city.',
    'world_mystic_woods': 'Mystic Woods',
    'desc_mystic_woods': 'An enchanted forest full of magic.',
    'world_void_nexus': 'Void Nexus',
    'desc_void_nexus': 'The space between dimensions.',
    'enemy_orc_grunt': 'Orc Grunt',
    'desc_orc_grunt': 'A brutish green warrior.',
    'enemy_dark_knight': 'Dark Knight',
    'desc_dark_knight': 'A fallen hero in black armor.',
    'enemy_dragon_whelp': 'Dragon Whelp',
    'desc_dragon_whelp': 'A small but deadly fire-breather.',
    'enemy_raptor_pack': 'Raptor Pack',
    'desc_raptor_pack': 'Clever girls hunting in a group.',
    'enemy_triceratops': 'Triceratops',
    'desc_triceratops': 'A three-horned herbivore with a bad temper.',
    'enemy_t_rex': 'T-Rex',
    'desc_t_rex': 'The King of the Dinosaurs.',
    'enemy_yakuza_bot': 'Yakuza Bot',
    'desc_yakuza_bot': 'A cybernetic gangster.',
    'enemy_cyber_ninja': 'Cyber Ninja',
    'desc_cyber_ninja': 'Fast, lethal, and invisible.',
    'enemy_goblin_thief': 'Goblin Thief',
    'desc_goblin_thief': 'He wants your gold!',
    'enemy_ent_guardian': 'Ent Guardian',
    'desc_ent_guardian': 'A walking tree protecting the forest.',
    'enemy_spirit_wolf': 'Spirit Wolf',
    'desc_spirit_wolf': 'A ghostly predator.',
    'enemy_void_stalker': 'Void Stalker',
    'desc_void_stalker': 'A creature that strikes from the shadows.',
    'item_strength_potion': 'Strength Potion',
    'desc_strength_potion': 'Damage Boost (1 Fight)',
    'item_iron_skin_potion': 'Iron Skin Potion',
    'desc_iron_skin_potion': 'Defense Boost (1 Fight)',
    'item_luck_charm': 'Luck Charm',
    'desc_luck_charm': 'Double Credits (1 Fight)',
    'weapon_excalibur': 'Excalibur',
    'weapon_bone_club': 'Bone Club',
    'weapon_laser_katana': 'Laser Katana',
    'weapon_magic_wand': 'Magic Wand',
    'weapon_void_cannon': 'Void Cannon',
    'encounter_chest_title': '🎁 Treasure Chest!',
    'encounter_chest_content': 'You found a hidden stash!\n\n+ \$%s Credits\n+ 1x %s',
    'encounter_shrine_title': '⛩️ Ancient Shrine',
    'encounter_shrine_content': 'You discover a glowing shrine. It radiates energy.',
    'action_claim': 'Claim',
    'action_pray': 'Pray (Heal)',
    'action_meditate': 'Meditate (Energy)',
    'msg_health_restored': 'Health Fully Restored!',
    'msg_energy_restored': 'Energy Fully Restored!',
    'msg_used_strength': 'Strength Potion Used: Damage Boost!',
    'msg_used_iron_skin': 'Iron Skin Potion Used: Defense Boost!',
    'msg_used_luck': 'Luck Charm Used: Double Credits!',
    'you_are_in': 'You are in %s.',
    'locked': 'Locked',
    'unlock_reach_floor': 'Reach Floor 100 in %s to unlock',
    'floor_label': 'FLOOR %s',
    'boss_warning': '⚠️ BOSS BATTLE ⚠️',
    'portal_label': 'Portal',
    'warp_msg': 'Warped to Floor %s',
    'explore_floor': 'EXPLORE FLOOR %s',
    'healing_spring': 'Found a Healing Spring! +50 HP',
  };

  static final Map<String, String> _es = {
    'app_title': 'Capitán Espacial',
    'tactical_log': 'Registro Táctico',
    'scan_enemies': 'ESCANEAR ENEMIGOS',
    'dock_station': 'ATRACAR EN ESTACIÓN',
    'attack': 'ATACAR',
    'heal': 'CURAR',
    'flee': 'HUIR',
    'energy': 'ENERGÍA',
    'credits': 'Créditos',
    'hp': 'PV',
    'xp': 'EXP',
    'blaster': 'Láser',
    'plasma_cannon': 'Cañón de Plasma',
    'shield': 'Escudo',
    'repair': 'Reparar',
    'recharge': 'RECARGAR',
    'station_title': 'Estación Espacial Alfa',
    'services': 'Servicios',
    'full_heal': 'Curación Completa',
    'restore_hp': 'Restaurar 100% PV',
    'armory': 'Armería',
    'travel': 'Viajar',
    'go': 'Ir',
    'warning_high_level': 'Advertencia: Nivel Alto',
    'shop': 'Tienda',
    'buy_credits': 'Comprar Créditos',
    'real_money': 'Dinero Real',
    'inventory': 'Inventario',
    'use': 'Usar',
    'empty_inventory': 'Inventario vacío',
    'tab_consumables': 'Consumibles',
    'tab_equipment': 'Equipo',
    'tab_bank': 'Banco',
    'item_energy_cell': 'Célula de Energía',
    'desc_energy_cell': '+50 Energía',
    'item_overcharge': 'Chip de Sobrecarga',
    'desc_overcharge': '+50% Daño (Siguiente Pelea)',
    'item_hyper_shield': 'Hiper-Escudo',
    'desc_hyper_shield': 'Inicia c/ 100 Escudo',
    'pack_small': 'Puñado de Créditos',
    'pack_medium': 'Saco de Créditos',
    'pack_large': 'Cofre de Créditos',
    'item_mega_potion': 'Mega-Poción',
    'desc_mega_potion': 'Cura 150 PV',
    'item_nano_elixir': 'Nano-Elixir',
    'desc_nano_elixir': 'Restaura 100 Energía',
    'item_titanium_plating': 'Blindaje Titanio',
    'desc_titanium_plating': '+20 Max PV',
    'item_neural_link': 'Enlace Neuronal',
    'desc_neural_link': '+10 Max Energía',
    'item_pulse_rifle': 'Rifle de Pulsos',
    'item_neutron_cannon': 'Cañón de Neutrones',
    'item_singularity': 'Proyector Singularidad',
    // Omni Realms Expansion
    'world_kingdom_valor': 'Reino del Valor',
    'desc_kingdom_valor': 'Una tierra medieval de caballeros y dragones.',
    'world_jurassica': 'Jurásica',
    'desc_jurassica': 'Una jungla prehistórica dominada por dinosaurios.',
    'world_neon_tokyo': 'Neón Tokio',
    'desc_neon_tokyo': 'Una ciudad ciberpunk futurista.',
    'world_mystic_woods': 'Bosque Místico',
    'desc_mystic_woods': 'Un bosque encantado lleno de magia.',
    'world_void_nexus': 'Nexo del Vacío',
    'desc_void_nexus': 'El espacio entre dimensiones.',
    'enemy_orc_grunt': 'Orco Grunt',
    'desc_orc_grunt': 'Un guerrero verde brutal.',
    'enemy_dark_knight': 'Caballero Oscuro',
    'desc_dark_knight': 'Un héroe caído con armadura negra.',
    'enemy_dragon_whelp': 'Cría de Dragón',
    'desc_dragon_whelp': 'Pequeño pero mortal escupefuego.',
    'enemy_raptor_pack': 'Manada de Raptores',
    'desc_raptor_pack': 'Chicas listas cazando en grupo.',
    'enemy_triceratops': 'Triceratops',
    'desc_triceratops': 'Herbívoro de tres cuernos con mal genio.',
    'enemy_t_rex': 'T-Rex',
    'desc_t_rex': 'El Rey de los Dinosaurios.',
    'enemy_yakuza_bot': 'Yakuza Bot',
    'desc_yakuza_bot': 'Un gánster cibernético.',
    'enemy_cyber_ninja': 'Ciber Ninja',
    'desc_cyber_ninja': 'Rápido, letal e invisible.',
    'enemy_goblin_thief': 'Goblin Ladrón',
    'desc_goblin_thief': '¡Quiere tu oro!',
    'enemy_ent_guardian': 'Ent Guardián',
    'desc_ent_guardian': 'Un árbol andante protegiendo el bosque.',
    'enemy_spirit_wolf': 'Lobo Espiritual',
    'desc_spirit_wolf': 'Un depredador fantasmal.',
    'enemy_void_stalker': 'Acechador del Vacío',
    'desc_void_stalker': 'Una criatura que ataca desde las sombras.',
    'item_strength_potion': 'Poción de Fuerza',
    'desc_strength_potion': 'Aumento de Daño (1 Pelea)',
    'item_iron_skin_potion': 'Poción Piel de Hierro',
    'desc_iron_skin_potion': 'Aumento de Defensa (1 Pelea)',
    'item_luck_charm': 'Amuleto de la Suerte',
    'desc_luck_charm': 'Créditos Dobles (1 Pelea)',
    'weapon_excalibur': 'Excalibur',
    'weapon_bone_club': 'Garrote de Hueso',
    'weapon_laser_katana': 'Katana Láser',
    'weapon_magic_wand': 'Varita Mágica',
    'weapon_void_cannon': 'Cañón del Vacío',
    'encounter_chest_title': '🎁 ¡Cofre del Tesoro!',
    'encounter_chest_content': '¡Encontraste un alijo oculto!\n\n+ \$%s Créditos\n+ 1x %s',
    'encounter_shrine_title': '⛩️ Santuario Antiguo',
    'encounter_shrine_content': 'Descubres un santuario brillante. Irradia energía.',
    'action_claim': 'Reclamar',
    'action_pray': 'Rezar (Curar)',
    'action_meditate': 'Meditar (Energía)',
    'msg_health_restored': '¡Salud Totalmente Restaurada!',
    'msg_energy_restored': '¡Energía Totalmente Restaurada!',
    'msg_used_strength': 'Poción de Fuerza Usada: ¡Aumento de Daño!',
    'msg_used_iron_skin': 'Poción Piel de Hierro Usada: ¡Aumento de Defensa!',
    'msg_used_luck': 'Amuleto de Suerte Usado: ¡Créditos Dobles!',
    'you_are_in': 'Estás en %s.',
    'locked': 'Bloqueado',
    'unlock_reach_floor': 'Llega al Piso 100 en %s para desbloquear',
    'floor_label': 'PISO %s',
    'boss_warning': '⚠️ BATALLA DE JEFE ⚠️',
    'portal_label': 'Portal',
    'warp_msg': 'Teletransportado al Piso %s',
    'explore_floor': 'EXPLORAR PISO %s',
    'healing_spring': '¡Manantial Curativo! +50 PV',
  };

  static final Map<String, String> _fr = {
    'app_title': 'Capitaine Spatial',
    'tactical_log': 'Journal Tactique',
    'scan_enemies': 'SCANNER ENNEMIS',
    'dock_station': 'AMARRER STATION',
    'attack': 'ATTAQUER',
    'heal': 'SOIGNER',
    'flee': 'FUIR',
    'energy': 'ÉNERGIE',
    'credits': 'Crédits',
    'hp': 'PV',
    'xp': 'EXP',
    'blaster': 'Blaster',
    'plasma_cannon': 'Canon Plasma',
    'shield': 'Bouclier',
    'repair': 'Réparer',
    'recharge': 'RECHARGER',
    'station_title': 'Station Spatiale Alpha',
    'services': 'Services',
    'full_heal': 'Soin Complet',
    'restore_hp': 'Restaurer 100% PV',
    'armory': 'Armurerie',
    'travel': 'Voyager',
    'go': 'Aller',
    'warning_high_level': 'Attention: Niveau Élevé',
    'shop': 'Boutique',
    'buy_credits': 'Acheter Crédits',
    'real_money': 'Argent Réel',
    'inventory': 'Inventaire',
    'use': 'Utiliser',
    'empty_inventory': 'Inventaire vide',
    'tab_consumables': 'Consommables',
    'tab_equipment': 'Équipement',
    'tab_bank': 'Banque',
    'item_energy_cell': 'Cellule Énergie',
    'desc_energy_cell': '+50 Énergie',
    'item_overcharge': 'Puce Surcharge',
    'desc_overcharge': '+50% Dégâts (Prochain Combat)',
    'item_hyper_shield': 'Hyper-Bouclier',
    'desc_hyper_shield': 'Début avec 100 Bouclier',
    'pack_small': 'Poignée de Crédits',
    'pack_medium': 'Sac de Crédits',
    'pack_large': 'Coffre de Crédits',
    'item_mega_potion': 'Méga-Potion',
    'desc_mega_potion': 'Soin 150 PV',
    'item_nano_elixir': 'Nano-Élixir',
    'desc_nano_elixir': 'Restaure 100 Énergie',
    'item_titanium_plating': 'Plaquage Titane',
    'desc_titanium_plating': '+20 Max PV',
    'item_neural_link': 'Lien Neuronal',
    'desc_neural_link': '+10 Max Énergie',
    'item_pulse_rifle': 'Fusil à Impulsion',
    'item_neutron_cannon': 'Canon à Neutrons',
    'item_singularity': 'Projecteur Singularité',
    // Omni Realms Expansion
    'world_kingdom_valor': 'Royaume de la Valeur',
    'desc_kingdom_valor': 'Une terre médiévale de chevaliers et de dragons.',
    'world_jurassica': 'Jurassica',
    'desc_jurassica': 'Une jungle préhistorique dominée par les dinosaures.',
    'world_neon_tokyo': 'Néon Tokyo',
    'desc_neon_tokyo': 'Une ville cyberpunk futuriste.',
    'world_mystic_woods': 'Bois Mystiques',
    'desc_mystic_woods': 'Une forêt enchantée pleine de magie.',
    'world_void_nexus': 'Nexus du Vide',
    'desc_void_nexus': 'L\'espace entre les dimensions.',
    'enemy_orc_grunt': 'Grunt Orc',
    'desc_orc_grunt': 'Un guerrier vert brutal.',
    'enemy_dark_knight': 'Chevalier Noir',
    'desc_dark_knight': 'Un héros déchu en armure noire.',
    'enemy_dragon_whelp': 'Bébé Dragon',
    'desc_dragon_whelp': 'Petit mais mortel cracheur de feu.',
    'enemy_raptor_pack': 'Meute de Raptors',
    'desc_raptor_pack': 'Des filles intelligentes chassant en groupe.',
    'enemy_triceratops': 'Tricératops',
    'desc_triceratops': 'Herbivore à trois cornes de mauvaise humeur.',
    'enemy_t_rex': 'T-Rex',
    'desc_t_rex': 'Le Roi des Dinosaures.',
    'enemy_yakuza_bot': 'Yakuza Bot',
    'desc_yakuza_bot': 'Un gangster cybernétique.',
    'enemy_cyber_ninja': 'Cyber Ninja',
    'desc_cyber_ninja': 'Rapide, mortel et invisible.',
    'enemy_goblin_thief': 'Voleur Gobelin',
    'desc_goblin_thief': 'Il veut votre or !',
    'enemy_ent_guardian': 'Ent Gardien',
    'desc_ent_guardian': 'Un arbre marchant protégeant la forêt.',
    'enemy_spirit_wolf': 'Loup Spirituel',
    'desc_spirit_wolf': 'Un prédateur fantomatique.',
    'enemy_void_stalker': 'Traqueur du Vide',
    'desc_void_stalker': 'Une créature qui frappe depuis les ombres.',
    'item_strength_potion': 'Potion de Force',
    'desc_strength_potion': 'Boost de Dégâts (1 Combat)',
    'item_iron_skin_potion': 'Potion Peau de Fer',
    'desc_iron_skin_potion': 'Boost de Défense (1 Combat)',
    'item_luck_charm': 'Charme de Chance',
    'desc_luck_charm': 'Crédits Doubles (1 Combat)',
    'weapon_excalibur': 'Excalibur',
    'weapon_bone_club': 'Massue en Os',
    'weapon_laser_katana': 'Katana Laser',
    'weapon_magic_wand': 'Baguette Magique',
    'weapon_void_cannon': 'Canon du Vide',
    'encounter_chest_title': '🎁 Coffre au Trésor !',
    'encounter_chest_content': 'Vous avez trouvé une cachette !\n\n+ \$%s Crédits\n+ 1x %s',
    'encounter_shrine_title': '⛩️ Sanctuaire Ancien',
    'encounter_shrine_content': 'Vous découvrez un sanctuaire brillant. Il rayonne d\'énergie.',
    'action_claim': 'Réclamer',
    'action_pray': 'Prier (Soin)',
    'action_meditate': 'Méditer (Énergie)',
    'msg_health_restored': 'Santé Entièrement Restaurée !',
    'msg_energy_restored': 'Énergie Entièrement Restaurée !',
    'msg_used_strength': 'Potion de Force Utilisée : Boost de Dégâts !',
    'msg_used_iron_skin': 'Potion Peau de Fer Utilisée : Boost de Défense !',
    'msg_used_luck': 'Charme de Chance Utilisé : Crédits Doubles !',
    'you_are_in': 'Vous êtes à %s.',
    'explore_floor': 'EXPLORER ÉTAGE %s',
    'healing_spring': 'Source de Guérison ! +50 PV',
  };

  static final Map<String, String> _pt = {
    'app_title': 'Capitão Espacial',
    'tactical_log': 'Registro Tático',
    'scan_enemies': 'ESCANEAR INIMIGOS',
    'dock_station': 'ACOPLAR NA ESTAÇÃO',
    'attack': 'ATACAR',
    'heal': 'CURAR',
    'flee': 'FUGIR',
    'energy': 'ENERGIA',
    'credits': 'Créditos',
    'hp': 'PV',
    'xp': 'EXP',
    'blaster': 'Blaster',
    'plasma_cannon': 'Canhão de Plasma',
    'shield': 'Escudo',
    'repair': 'Reparar',
    'recharge': 'RECARREGAR',
    'station_title': 'Estação Espacial Alfa',
    'services': 'Serviços',
    'full_heal': 'Cura Completa',
    'restore_hp': 'Restaurar 100% PV',
    'armory': 'Arsenal',
    'travel': 'Viajar',
    'go': 'Ir',
    'warning_high_level': 'Aviso: Nível Alto',
    'shop': 'Loja',
    'buy_credits': 'Comprar Créditos',
    'real_money': 'Dinheiro Real',
    'inventory': 'Inventário',
    'use': 'Usar',
    'empty_inventory': 'Inventário vazio',
    'tab_consumables': 'Consumíveis',
    'tab_equipment': 'Equipamento',
    'tab_bank': 'Banco',
    'item_energy_cell': 'Célula de Energia',
    'desc_energy_cell': '+50 Energia',
    'item_overcharge': 'Chip de Sobrecarga',
    'desc_overcharge': '+50% Dano (Próxima Luta)',
    'item_hyper_shield': 'Hiper-Escudo',
    'desc_hyper_shield': 'Começa c/ 100 Escudo',
    'pack_small': 'Punhado de Créditos',
    'pack_medium': 'Saco de Créditos',
    'pack_large': 'Baú de Créditos',
    'item_mega_potion': 'Mega-Poção',
    'desc_mega_potion': 'Cura 150 PV',
    'item_nano_elixir': 'Nano-Elixir',
    'desc_nano_elixir': 'Restaura 100 Energia',
    'item_titanium_plating': 'Blindagem Titânio',
    'desc_titanium_plating': '+20 Max PV',
    'item_neural_link': 'Link Neuronal',
    'desc_neural_link': '+10 Max Energia',
    'item_pulse_rifle': 'Rifle de Pulso',
    'item_neutron_cannon': 'Canhão de Nêutrons',
    'item_singularity': 'Projetor Singularidade',
    // Omni Realms Expansion
    'world_kingdom_valor': 'Reino do Valor',
    'desc_kingdom_valor': 'Uma terra medieval de cavaleiros e dragões.',
    'world_jurassica': 'Jurássica',
    'desc_jurassica': 'Uma selva pré-histórica dominada por dinossauros.',
    'world_neon_tokyo': 'Neon Tóquio',
    'desc_neon_tokyo': 'Uma cidade cyberpunk futurista.',
    'world_mystic_woods': 'Bosque Místico',
    'desc_mystic_woods': 'Uma floresta encantada cheia de magia.',
    'world_void_nexus': 'Nexus do Vazio',
    'desc_void_nexus': 'O espaço entre dimensões.',
    'enemy_orc_grunt': 'Orc Grunt',
    'desc_orc_grunt': 'Um guerreiro verde brutal.',
    'enemy_dark_knight': 'Cavaleiro das Trevas',
    'desc_dark_knight': 'Um herói caído em armadura negra.',
    'enemy_dragon_whelp': 'Filhote de Dragão',
    'desc_dragon_whelp': 'Pequeno mas mortal cuspidor de fogo.',
    'enemy_raptor_pack': 'Bando de Raptors',
    'desc_raptor_pack': 'Garotas espertas caçando em grupo.',
    'enemy_triceratops': 'Tricerátops',
    'desc_triceratops': 'Herbívoro de três chifres com mau humor.',
    'enemy_t_rex': 'T-Rex',
    'desc_t_rex': 'O Rei dos Dinossauros.',
    'enemy_yakuza_bot': 'Yakuza Bot',
    'desc_yakuza_bot': 'Um gângster cibernético.',
    'enemy_cyber_ninja': 'Cyber Ninja',
    'desc_cyber_ninja': 'Rápido, letal e invisível.',
    'enemy_goblin_thief': 'Goblin Ladrão',
    'desc_goblin_thief': 'Ele quer seu ouro!',
    'enemy_ent_guardian': 'Ent Guardião',
    'desc_ent_guardian': 'Uma árvore andante protegendo a floresta.',
    'enemy_spirit_wolf': 'Lobo Espiritual',
    'desc_spirit_wolf': 'Um predador fantasmagórico.',
    'enemy_void_stalker': 'Perseguidor do Vazio',
    'desc_void_stalker': 'Uma criatura que ataca das sombras.',
    'item_strength_potion': 'Poção de Força',
    'desc_strength_potion': 'Aumento de Dano (1 Luta)',
    'item_iron_skin_potion': 'Poção Pele de Ferro',
    'desc_iron_skin_potion': 'Aumento de Defesa (1 Luta)',
    'item_luck_charm': 'Amuleto da Sorte',
    'desc_luck_charm': 'Créditos em Dobro (1 Luta)',
    'weapon_excalibur': 'Excalibur',
    'weapon_bone_club': 'Clava de Osso',
    'weapon_laser_katana': 'Katana Laser',
    'weapon_magic_wand': 'Varinha Mágica',
    'weapon_void_cannon': 'Canhão do Vazio',
    'encounter_chest_title': '🎁 Baú do Tesouro!',
    'encounter_chest_content': 'Você encontrou um esconderijo!\n\n+ \$%s Créditos\n+ 1x %s',
    'encounter_shrine_title': '⛩️ Santuário Antigo',
    'encounter_shrine_content': 'Você descobre um santuário brilhante. Ele irradia energia.',
    'action_claim': 'Resgatar',
    'action_pray': 'Rezar (Curar)',
    'action_meditate': 'Meditar (Energia)',
    'msg_health_restored': 'Saúde Totalmente Restaurada!',
    'msg_energy_restored': 'Energia Totalmente Restaurada!',
    'msg_used_strength': 'Poção de Força Usada: Aumento de Dano!',
    'msg_used_iron_skin': 'Poção Pele de Ferro Usada: Aumento de Defesa!',
    'msg_used_luck': 'Amuleto da Sorte Usado: Créditos em Dobro!',
    'you_are_in': 'Você está em %s.',
    'explore_floor': 'EXPLORAR ANDAR %s',
    'healing_spring': 'Fonte Curativa! +50 PV',
  };
}
