name: pixel_art_game
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- AQUÍ ESTÁ EL CAMBIO ---
  # 'image' ahora está alineado a la izquierda, igual que 'flutter'
  image: ^4.2.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # --- CONFIGURACIÓN DE ASSETS ---
  # Esto le dice a la app que use la carpeta que creaste
  assets:
    - assets/