// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnSU-b7UgScNSyOb9dTezuHEoJ36z_9I',
    appId: '1:30632730598:web:cc8e398899095bc6628027',
    messagingSenderId: '30632730598',
    projectId: 'jovi-45c79',
    authDomain: 'jovi-45c79.firebaseapp.com',
    storageBucket: 'jovi-45c79.firebasestorage.app',
    measurementId: 'G-6Y1KRN56PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHcaIdbiGKOzYuZGjPlFP4GlS4gSad9fw',
    appId: '1:30632730598:android:b567c9426c549a99628027',
    messagingSenderId: '30632730598',
    projectId: 'jovi-45c79',
    storageBucket: 'jovi-45c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJBc6yxdCeP-rNifKIdn9nxCKnj84K2E',
    appId: '1:30632730598:ios:251722ce91159af5628027',
    messagingSenderId: '30632730598',
    projectId: 'jovi-45c79',
    storageBucket: 'jovi-45c79.firebasestorage.app',
    iosBundleId: 'com.example.joviArApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJBc6yxdCeP-rNifKIdn9nxCKnj84K2E',
    appId: '1:30632730598:ios:251722ce91159af5628027',
    messagingSenderId: '30632730598',
    projectId: 'jovi-45c79',
    storageBucket: 'jovi-45c79.firebasestorage.app',
    iosBundleId: 'com.example.joviArApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNnSU-b7UgScNSyOb9dTezuHEoJ36z_9I',
    appId: '1:30632730598:web:b1c8f1aecedb5212628027',
    messagingSenderId: '30632730598',
    projectId: 'jovi-45c79',
    authDomain: 'jovi-45c79.firebaseapp.com',
    storageBucket: 'jovi-45c79.firebasestorage.app',
    measurementId: 'G-SK0KCL2Y19',
  );
}
